server:
  port: 9999
spring:
  main:
    web-application-type: reactive
  application:
    name:  gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/notification/**
            - id: BE
              uri: lb://BE
              predicates:
                - Path=/api/user/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


