spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:mysql://localhost:3306/notification?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka



common:
  kafka:
    bootstrap-servers: localhost 9092
    group-id: "hello"

